codeunit 52203437 "Payment Management"
{
    Permissions = tabledata "Purch. Inv. Header"=rm,
        tabledata "Purch. Inv. Line"=rm;

    var Window: Dialog;
    Names: Text;
    Counter: Integer;
    Text002: Label 'This request %1  has not been approved';
    Text004: Label 'Are you sure you want to process Payment request for %1?';
    Text005: Label 'The document %1 has been requested for Payment.';
    Text006: Label 'Payment request has been created successfully.';
    Text007: Label 'There is nothing to review!';
    procedure CreatePVforRequestForPayment(var Request: Record "Request for Payment"; PurchInvHeader: Record "Purch. Inv. Header")
    var
        PV: Record "Payment Voucher";
        RPLines: Record "Request for Payment Lines";
        LineNo: Integer;
        DocumentAttachment: Record "Document Attachment";
        DocumentAttachment2: Record "Document Attachment";
    begin
        // if Confirm(Text001, false) = true then begin
        if Request.Status <> Request.Status::Approved then Error(Text002, Request."No.");
        Request.TestField("Creditor No.");
        // if "PV Generated" then
        //     //PV Header
        PV.Init;
        PV."Payment Type":=PV."Payment Type"::"Supplier Payment";
        PV."Global Dimension 1 Code":=Request."Global Dimension 1 Code";
        PV."Global Dimension 2 Code":=Request."Global Dimension 2 Code";
        PV."From Self Service":=true;
        PV.Status:=PV.Status::Open;
        PV.Description:=Request.Description;
        PV.Date:=WorkDate;
        PV."Prepared By":=UserId;
        PV.Insert(true);
        DocumentAttachment.Reset();
        DocumentAttachment.SetRange("Table ID", Database::"Purch. Inv. Header");
        DocumentAttachment.SetRange("No.", PurchInvHeader."No.");
        if DocumentAttachment.FindSet()then begin
            repeat DocumentAttachment2.Init();
                DocumentAttachment2.TransferFields(DocumentAttachment);
                DocumentAttachment2."Table ID":=Database::"Payment Voucher";
                DocumentAttachment2."No.":=PV."No.";
                DocumentAttachment2.Insert(true);
            until DocumentAttachment.Next() = 0;
        end;
        //Lines
        LineNo:=10000;
        RPLines.Reset;
        RPLines.SetRange("No.", Request."No.");
        if RPLines.FindSet then begin
            repeat LineNo:=LineNo + 1000;
                CreatePVLines(Request, RPLines, PV, LineNo);
            until RPLines.Next = 0;
        end
        else
            Error('The Request has been marked as Split Payment but there are not split details.');
        Request."PV No.":=PV."No.";
        Request."PV Generated":=true;
        Request."PV Generated By":=UserId;
        Request."PV Generated Date":=CurrentDateTime;
        Request.Modify;
        Message('Payment Voucher Number %1 has been created for this Request.', PV."No.");
        Commit;
        PAGE.Run(Page::"Payment Request", PV);
    end;
    local procedure CreatePVLines(Request: Record "Request for Payment"; RPLines: Record "Request for Payment Lines"; PVHeader: Record "Payment Voucher"; LineNo: Integer)
    var
        BeneficiaryBanks: Record "Payee Bank Details";
        PVLines: Record "Payment Voucher Lines";
        ITO: Record "Request Header";
    begin
        PVLines.Init;
        PVLines.Validate("No.", PVHeader."No.");
        PVLines."Line No":=LineNo;
        PVLines.Validate("Payment Type", PVHeader."Payment Type");
        if RPLines."Source Document" = RPLines."Source Document"::"Travel Order" then PVLines."Account Type":=PVLines."Account Type"::Customer;
        PVLines.Validate("Account No", RPLines."Creditor No.");
        PVLines.Validate("Account Name", RPLines."Name of Creditor");
        if Request."Source Document" = Request."Source Document"::"Supplier Invoice" then begin
            PVLines.Validate("Applies to Doc. No", RPLines."Source Document No.");
            if PVHeader."Payment Type" = PVHeader."Payment Type"::"Supplier Payment" then begin
                BeneficiaryBanks.Reset();
                BeneficiaryBanks.SetRange("Vendor No", RPLines."Creditor No.");
                BeneficiaryBanks.SetRange(Active, true);
                if BeneficiaryBanks.FindFirst then begin
                    PVLines.Validate(Payee, BeneficiaryBanks."Beneficiary Name");
                    PVLines.Validate("Payee Bank Code", BeneficiaryBanks."Bank Code");
                    PVLines.Validate("Payee Bank Branch Code", BeneficiaryBanks."Branch Code");
                    PVLines.Validate("Payee Account No.", BeneficiaryBanks."Bank Account Number");
                end;
            end;
        end;
        PVLines.Description:=RPLines."Being Payment for";
        PVLines.Validate("Currency Code", RPLines."Currency Code");
        PVLines.Validate(Amount, RPLines.Amount);
        PVLines.Validate("Purchase Invoice Amount", RPLines."Purchase Invoice Amount");
        PVLines.Validate("Outstanding Amount", RPLines."Outstanding Amount");
        PVLines."Purchase Invoice Amount":=RPLines."Purchase Invoice Amount";
        PVLines."Global Dimension 1 Code":=RPLines."Global Dimension 1 Code";
        PVLines."Global Dimension 2 Code":=RPLines."Global Dimension 2 Code";
        PVLines.Insert(true);
        if RPLines."Source Document" = RPLines."Source Document"::"Travel Order" then begin
            if ITO.Get(RPLines."Source Document No.")then begin
                ITO.Posted:=true;
                ITO."Posted By":=UserId;
                ITO."Posted Date":=WorkDate;
                ITO."Request Type":=ITO."Request Type"::Surrender;
                ITO.Modify;
            end;
        end;
    end;
    procedure ViewPVForRequestForPayment(var Request: Record "Request for Payment")
    var
        FormerPVNo: Code[20];
        LatterPVNo: Code[20];
        PV: Record "Payment Voucher";
    begin
        with Request do begin
            PV.Reset;
            PV.SetRange("No.", Request."PV No.");
            if PV.FindFirst then begin
                PAGE.RunModal(50028, PV, PV."No.");
            end;
        end;
    end;
    procedure InvoicePaymentRequest(Var Invoice: Record "Purch. Inv. Header")
    var
        PurchInv: Record "Purch. Inv. Header";
        PurchaseHeader: Record "Purchase Header";
    begin
        with Invoice do begin
            if Confirm(StrSubstNo(Text004, "No."), false) = true then begin
                if "Payment Requested" then Error(StrSubstNo(Text005, "No."));
                PurchInv.Reset();
                PurchInv.SetRange("No.", "No.");
                PurchInv.SetRange("Payment Requested", false);
                if PurchInv.FindFirst()then begin
                    PurchInv.Decision:=PurchInv.Decision::NEW;
                    if PAGE.RunModal(PAGE::"Payment Req Review", PurchInv) = ACTION::LookupOK then begin
                        PurchInv.TestField(Decision);
                        if PurchInv.Decision = PurchInv.Decision::Append then PurchInv.TestField(Target);
                        PurchInv.TestField("Amount To Request");
                        ExecutePaymentRequestReview(true, PurchInv."No.");
                        Message(Text006);
                    end
                    else
                    begin
                        exit;
                    end;
                end;
                Commit;
            end;
        end end;
    procedure ExecutePaymentRequestReview(SingleExecute: Boolean; InvoiceNo: Code[20])
    var
        Request: Record "Request for Payment";
        RequestLines: Record "Request for Payment Lines";
        PurchInvoice: Record "Purch. Inv. Header";
        DocumentAttachment: Record "Document Attachment";
        DocumentAttachment2: Record "Document Attachment";
    begin
        Counter:=0;
        Names:='';
        Window.Open('Processing Payment Request Review #####1 for #####2', Counter, Names);
        PurchInvoice.Reset();
        if SingleExecute then PurchInvoice.SetRange("No.", InvoiceNo);
        PurchInvoice.SetRange("Payment Requested", false);
        PurchInvoice.SetFilter(Decision, '<>%1', PurchInvoice.Decision::" ");
        PurchInvoice.SetRange("Decision By", UserId);
        PurchInvoice.SetFilter("Amount To Request", '<>%1', 0);
        If PurchInvoice.Find('-')then begin
            repeat Counter:=Counter + 1;
                if PurchInvoice.Decision = PurchInvoice.Decision::New then CreateRequestForInvoice(PurchInvoice);
                if((PurchInvoice.Decision = PurchInvoice.Decision::"Append") and (PurchInvoice.Target <> ''))then Window.Update(1, Counter);
                Window.Update(2, PurchInvoice."Buy-from Vendor Name");
            until PurchInvoice.Next = 0;
            Message(Text006);
            Window.Close();
        end
        else
            Error(Text007);
    end;
    local procedure AppendInvoiceToPaymentRequest(var Invoice: Record "Purch. Inv. Header")
    var
        LineCount: Integer;
        LineNo: Integer;
        Request: Record "Request for Payment";
        RequestLines: Record "Request for Payment Lines";
    begin
        with Invoice do begin
            //Request For Payment
            Request.Reset();
            Request.SetRange("No.", Target);
            If Request.FindFirst()then begin
                RequestLines.Reset();
                RequestLines.SetRange("No.", Request."No.");
                LineCount:=RequestLines.Count + 1;
                LineNo:=LineCount * 1000;
                CreatePaymentRequestLines(Request, Invoice, LineNo);
            end;
        end;
    end;
    local procedure CreateRequestForInvoice(var Invoice: Record "Purch. Inv. Header")
    var
        Payment: Record "Request for Payment";
    begin
        with Invoice do begin
            //Request For Payment
            Payment.Init;
            Payment."Source Document":=Payment."Source Document"::"Supplier Invoice";
            Payment.Validate("Creditor No.", "Buy-from Vendor No.");
            Payment."Global Dimension 1 Code":=Invoice."Shortcut Dimension 1 Code";
            Payment."Global Dimension 2 Code":=Invoice."Shortcut Dimension 2 Code";
            Payment.Description:=Invoice."Posting Description";
            Payment.Status:=Payment.Status::Approved;
            Payment.Insert(true);
            Commit;
            CreatePaymentRequestLines(Payment, Invoice, 1000);
        end;
    end;
    local procedure CreatePaymentRequestLines(var PaymentRequest: Record "Request for Payment"; PurchInvHeader: Record "Purch. Inv. Header"; LineNo: Integer)
    var
        RequestLines: Record "Request for Payment Lines";
    begin
        with PurchInvHeader do begin
            RequestLines.Init;
            RequestLines."No.":=PaymentRequest."No.";
            RequestLines."Line No.":=LineNo;
            RequestLines."Source Document":=RequestLines."Source Document"::"Supplier Invoice";
            RequestLines.Validate("Source Document No.", "No.");
            RequestLines.Validate("Creditor No.", "Buy-from Vendor No.");
            RequestLines."Invoice No.":="Vendor Invoice No.";
            RequestLines."Currency Code":="Currency Code";
            RequestLines."Global Dimension 1 Code":="Shortcut Dimension 1 Code";
            RequestLines."Global Dimension 2 Code":="Shortcut Dimension 2 Code";
            RequestLines."Being Payment for":="Posting Description";
            RequestLines.Amount:="Amount To Request";
            CalcFields(Amount, "Remaining Amount", "Amount Including VAT");
            if "Amount Including VAT" <> 0 then RequestLines."Purchase Invoice Amount":="Amount Including VAT"
            else
                RequestLines."Purchase Invoice Amount":="Remaining Amount";
            RequestLines."Outstanding Amount":="Amount Remaining To Request";
            RequestLines.Insert(true);
            PaymentRequest.Status:=PaymentRequest.Status::Approved;
            PaymentRequest.Modify(true);
            CreatePVforRequestForPayment(PaymentRequest, PurchInvHeader);
            "Amount Remaining To Request":="Amount Remaining To Request" - "Amount To Request";
            if "Amount Remaining To Request" <> 0 then begin
                "Partial Payment Request":=true;
                "Payment Requested":=false;
            end
            else
                "Payment Requested":=true;
            Modify(true);
        end;
    end;
}
