-- Tier One SACCO — initial PostgreSQL schema.
--
-- Translated from the original SQLite DDL. Three differences matter:
--
--  1. Money is `bigint`, not `integer`. SQLite's INTEGER is 8 bytes, so cent
--     amounts over 2^31 were fine; PostgreSQL's `integer` is 4 bytes and the
--     live data already holds gl_account.balance = 3,145,100,000. Every
--     monetary column is bigint.
--  2. Identity columns are GENERATED BY DEFAULT, not ALWAYS, so a data import
--     can carry the original ids across.
--  3. Flags stay `integer` 0/1 rather than boolean, to keep the application's
--     existing comparisons (`is_postable = 1`) working unchanged.

-- ============================================================ ADMIN / ORG
CREATE TABLE organisation (
  id                integer PRIMARY KEY CHECK (id = 1),
  name              text NOT NULL,
  short_name        text,
  motto             text,
  registration_no   text,
  sasra_licence_no  text,
  kra_pin           text,
  society_type      text DEFAULT 'Deposit Taking SACCO',
  physical_address  text,
  postal_address    text,
  city              text,
  county            text,
  country           text DEFAULT 'Kenya',
  phone_primary     text,
  phone_secondary   text,
  email             text,
  website           text,
  paybill_no        text,
  bank_name         text,
  bank_account_no   text,
  logo              text,              -- Cloudinary public_id (legacy: data: URL)
  currency_code     text DEFAULT 'KES',
  currency_symbol   text DEFAULT 'KSh',
  locale            text DEFAULT 'en-KE',
  timezone          text DEFAULT 'Africa/Nairobi',
  date_format       text DEFAULT 'dd MMM yyyy',
  fy_start_month    integer DEFAULT 1,
  fy_start_day      integer DEFAULT 1,
  statement_footer  text,
  updated_at        text,
  updated_by        text
);

CREATE TABLE theme (
  id            integer PRIMARY KEY CHECK (id = 1),
  preset        text DEFAULT 'custom',
  tokens        text NOT NULL,
  updated_at    text,
  updated_by    text
);

CREATE TABLE branch (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           text NOT NULL UNIQUE,
  name           text NOT NULL,
  town           text,
  phone          text,
  is_head_office integer NOT NULL DEFAULT 0,
  status         text NOT NULL DEFAULT 'ACTIVE',
  created_at     text
);

CREATE TABLE role (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  description text,
  is_system   integer NOT NULL DEFAULT 0,
  permissions text NOT NULL DEFAULT '[]'
);

CREATE TABLE app_user (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL UNIQUE,
  full_name     text NOT NULL,
  email         text,
  phone         text,
  password_hash text NOT NULL,
  role_id       integer NOT NULL REFERENCES role(id),
  branch_id     integer REFERENCES branch(id),
  status        text NOT NULL DEFAULT 'ACTIVE',
  last_login_at text,
  created_at    text
);
CREATE INDEX ix_user_role ON app_user(role_id);

CREATE TABLE session (
  token      text PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES app_user(id),
  created_at text,
  expires_at text
);

CREATE TABLE audit_log (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at        text NOT NULL,
  user_id   integer,
  username  text,
  action    text NOT NULL,
  entity    text,
  entity_id text,
  detail    text,
  ip        text
);
CREATE INDEX ix_audit_at ON audit_log(at DESC);

CREATE TABLE sequence (
  name    text PRIMARY KEY,
  prefix  text NOT NULL DEFAULT '',
  next_no integer NOT NULL DEFAULT 1,
  width   integer NOT NULL DEFAULT 6
);

-- ============================================================ MEMBERS
CREATE TABLE member (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_no         text NOT NULL UNIQUE,
  member_type       text NOT NULL DEFAULT 'INDIVIDUAL',
  title             text,
  first_name        text NOT NULL,
  middle_name       text,
  last_name         text NOT NULL,
  national_id       text,
  kra_pin           text,
  date_of_birth     text,
  gender            text,
  marital_status    text,
  phone             text,
  email             text,
  postal_address    text,
  physical_address  text,
  county            text,
  employer          text,
  employment_status text,
  staff_no          text,
  gross_income      bigint NOT NULL DEFAULT 0,
  other_deductions  bigint NOT NULL DEFAULT 0,
  nok_name          text,
  nok_relationship  text,
  nok_phone         text,
  branch_id         integer REFERENCES branch(id),
  status            text NOT NULL DEFAULT 'ACTIVE',
  kyc_verified      integer NOT NULL DEFAULT 0,
  join_date         text,
  photo             text,
  notes             text,
  created_at        text,
  created_by        text
);
CREATE INDEX ix_member_name ON member(last_name, first_name);
CREATE INDEX ix_member_status ON member(status);
CREATE UNIQUE INDEX ux_member_nid ON member(national_id)
  WHERE national_id IS NOT NULL AND national_id <> '';

-- ============================================================ CHART OF ACCOUNTS
CREATE TABLE gl_account (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        text NOT NULL UNIQUE,
  name        text NOT NULL,
  type        text NOT NULL,
  parent_code text,
  is_postable integer NOT NULL DEFAULT 1,
  balance     bigint NOT NULL DEFAULT 0,
  status      text NOT NULL DEFAULT 'ACTIVE'
);

-- ============================================================ JOURNALS
CREATE TABLE journal (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_no      text NOT NULL UNIQUE,
  value_date      text NOT NULL,
  posted_at       text NOT NULL,
  source_module   text NOT NULL,
  event_type      text NOT NULL,
  description     text,
  reference       text,
  member_id       integer REFERENCES member(id),
  amount          bigint NOT NULL,
  posted_by       text,
  reverses_id     integer REFERENCES journal(id),
  reversed_by_id  integer REFERENCES journal(id),
  idempotency_key text UNIQUE
);
CREATE INDEX ix_journal_date ON journal(value_date);

CREATE TABLE journal_line (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id    integer NOT NULL REFERENCES journal(id),
  line_no       integer NOT NULL,
  gl_account_id integer NOT NULL REFERENCES gl_account(id),
  debit         bigint NOT NULL DEFAULT 0,
  credit        bigint NOT NULL DEFAULT 0,
  narration     text,
  CHECK (debit >= 0 AND credit >= 0),
  CHECK (NOT (debit > 0 AND credit > 0))
);
CREATE INDEX ix_jl_journal ON journal_line(journal_id);
CREATE INDEX ix_jl_account ON journal_line(gl_account_id);

CREATE TABLE accounting_period (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       text NOT NULL UNIQUE,
  start_date text NOT NULL,
  end_date   text NOT NULL,
  status     text NOT NULL DEFAULT 'OPEN'
);

-- ============================================================ BOSA / SAVINGS
CREATE TABLE savings_product (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                   text NOT NULL UNIQUE,
  name                   text NOT NULL,
  category               text NOT NULL DEFAULT 'SAVINGS',
  min_balance            bigint NOT NULL DEFAULT 0,
  min_opening            bigint NOT NULL DEFAULT 0,
  interest_rate          double precision NOT NULL DEFAULT 0,
  allow_withdrawal       integer NOT NULL DEFAULT 1,
  withdrawal_fee         bigint NOT NULL DEFAULT 0,
  is_loanable_base       integer NOT NULL DEFAULT 0,
  withdrawal_notice_days integer NOT NULL DEFAULT 0,
  gl_control_id          integer REFERENCES gl_account(id),
  gl_interest_exp_id     integer REFERENCES gl_account(id),
  gl_fee_income_id       integer REFERENCES gl_account(id),
  status                 text NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE savings_account (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_no    text NOT NULL UNIQUE,
  member_id     integer NOT NULL REFERENCES member(id),
  product_id    integer NOT NULL REFERENCES savings_product(id),
  balance       bigint NOT NULL DEFAULT 0,
  hold_amount   bigint NOT NULL DEFAULT 0,
  status        text NOT NULL DEFAULT 'ACTIVE',
  opened_date   text,
  last_activity text,
  version       integer NOT NULL DEFAULT 0
);
CREATE INDEX ix_sa_member ON savings_account(member_id);
CREATE INDEX ix_sa_product ON savings_account(product_id);

-- ============================================================ LOANS
CREATE TABLE loan_product (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code                  text NOT NULL UNIQUE,
  name                  text NOT NULL,
  interest_rate         double precision NOT NULL DEFAULT 12,
  interest_method       text NOT NULL DEFAULT 'REDUCING',
  max_term_months       integer NOT NULL DEFAULT 48,
  min_amount            bigint NOT NULL DEFAULT 0,
  max_amount            bigint NOT NULL DEFAULT 500000000,
  deposit_multiplier    double precision NOT NULL DEFAULT 3,
  min_membership_months integer NOT NULL DEFAULT 6,
  processing_fee_pct    double precision NOT NULL DEFAULT 1,
  insurance_pct         double precision NOT NULL DEFAULT 0.5,
  penalty_rate          double precision NOT NULL DEFAULT 1,
  guarantors_required   integer NOT NULL DEFAULT 2,
  max_dsr_pct           double precision NOT NULL DEFAULT 66.7,
  gl_receivable_id      integer REFERENCES gl_account(id),
  gl_interest_income_id integer REFERENCES gl_account(id),
  gl_fee_income_id      integer REFERENCES gl_account(id),
  gl_penalty_income_id  integer REFERENCES gl_account(id),
  status                text NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE loan (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_no                text NOT NULL UNIQUE,
  member_id              integer NOT NULL REFERENCES member(id),
  product_id             integer NOT NULL REFERENCES loan_product(id),
  principal              bigint NOT NULL,
  interest_rate          double precision NOT NULL,
  interest_method        text NOT NULL,
  term_months            integer NOT NULL,
  purpose                text,
  status                 text NOT NULL DEFAULT 'PENDING',
  applied_date           text,
  approved_date          text,
  approved_by            text,
  rejected_reason        text,
  disbursed_date         text,
  first_due_date         text,
  installment            bigint NOT NULL DEFAULT 0,
  total_interest         bigint NOT NULL DEFAULT 0,
  fees_charged           bigint NOT NULL DEFAULT 0,
  principal_balance      bigint NOT NULL DEFAULT 0,
  interest_balance       bigint NOT NULL DEFAULT 0,
  penalty_balance        bigint NOT NULL DEFAULT 0,
  principal_paid         bigint NOT NULL DEFAULT 0,
  interest_paid          bigint NOT NULL DEFAULT 0,
  arrears_amount         bigint NOT NULL DEFAULT 0,
  days_in_arrears        integer NOT NULL DEFAULT 0,
  classification         text NOT NULL DEFAULT 'PERFORMING',
  disburse_to_account_id integer REFERENCES savings_account(id),
  created_by             text,
  version                integer NOT NULL DEFAULT 0
);
CREATE INDEX ix_loan_member ON loan(member_id);
CREATE INDEX ix_loan_status ON loan(status);
CREATE INDEX ix_loan_product ON loan(product_id);

CREATE TABLE loan_schedule (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id         integer NOT NULL REFERENCES loan(id),
  installment_no  integer NOT NULL,
  due_date        text NOT NULL,
  opening_balance bigint NOT NULL DEFAULT 0,
  principal_due   bigint NOT NULL DEFAULT 0,
  interest_due    bigint NOT NULL DEFAULT 0,
  principal_paid  bigint NOT NULL DEFAULT 0,
  interest_paid   bigint NOT NULL DEFAULT 0,
  status          text NOT NULL DEFAULT 'DUE'
);
CREATE INDEX ix_ls_loan ON loan_schedule(loan_id, installment_no);

CREATE TABLE loan_guarantor (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id   integer NOT NULL REFERENCES loan(id),
  member_id integer NOT NULL REFERENCES member(id),
  amount    bigint NOT NULL DEFAULT 0,
  status    text NOT NULL DEFAULT 'COMMITTED',
  UNIQUE(loan_id, member_id)
);
CREATE INDEX ix_lg_member ON loan_guarantor(member_id);

-- ============================================================ TRANSACTIONS
CREATE TABLE txn (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_ref            text NOT NULL UNIQUE,
  value_date         text NOT NULL,
  created_at         text NOT NULL,
  module             text NOT NULL,
  txn_type           text NOT NULL,
  member_id          integer REFERENCES member(id),
  savings_account_id integer REFERENCES savings_account(id),
  loan_id            integer REFERENCES loan(id),
  amount             bigint NOT NULL,
  running_balance    bigint,
  channel            text DEFAULT 'TELLER',
  description        text,
  journal_id         integer REFERENCES journal(id),
  created_by         text,
  status             text NOT NULL DEFAULT 'POSTED',
  reversal_of        integer REFERENCES txn(id)
);
CREATE INDEX ix_txn_sa ON txn(savings_account_id, id);
CREATE INDEX ix_txn_loan ON txn(loan_id, id);
CREATE INDEX ix_txn_date ON txn(value_date);
CREATE INDEX ix_txn_member ON txn(member_id, id DESC);

-- ============================================================ ATTACHMENTS
CREATE TABLE attachment (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity        text NOT NULL,
  entity_id     integer NOT NULL,
  public_id     text NOT NULL UNIQUE,
  url           text NOT NULL,
  filename      text NOT NULL,
  resource_type text NOT NULL DEFAULT 'image',
  format        text,
  bytes         integer NOT NULL DEFAULT 0,
  category      text,
  uploaded_at   text NOT NULL,
  uploaded_by   text NOT NULL
);
CREATE INDEX ix_attachment_entity ON attachment(entity, entity_id, id DESC);

-- ============================================================ WORKFLOW
CREATE TABLE approval_task (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity     text NOT NULL,
  entity_id  integer NOT NULL,
  action     text NOT NULL,
  amount     bigint DEFAULT 0,
  maker      text NOT NULL,
  maker_at   text NOT NULL,
  checker    text,
  checker_at text,
  decision   text NOT NULL DEFAULT 'PENDING',
  reason     text,
  payload    text
);
CREATE INDEX ix_task_decision ON approval_task(decision);
