-- Role Centres + Profiles — a Business Central port.
--
-- A "Profile" is a landing-page selector: it decides which Role Centre (tailored home dashboard)
-- a user sees, and NOTHING else. It grants no permissions — the existing Permission Set system
-- (role + permission_set_line) is untouched and fully independent. An admin assigns one or more
-- Profiles to a user; the user switches the active one from My Settings.

-- ============================================================================= profile catalogue

CREATE TABLE "profile" (
    "id"          SERIAL NOT NULL,
    "code"        TEXT   NOT NULL,
    "name"        TEXT   NOT NULL,
    "description" TEXT   NOT NULL DEFAULT '',
    -- The Role Centre this profile lands on. Equals `code` for the six seeded profiles; a
    -- separate column so an admin-added profile can reuse an existing centre.
    "role_centre" TEXT   NOT NULL DEFAULT 'SUPER',
    "icon"        TEXT   NOT NULL DEFAULT '',
    "sort"        INTEGER NOT NULL DEFAULT 0,
    -- The fallback centre when a user has profiles assigned but no active one chosen.
    "is_default"  INTEGER NOT NULL DEFAULT 0,
    -- Seeded rows are system profiles: their code + role_centre are locked in the admin UI.
    "is_system"   INTEGER NOT NULL DEFAULT 0,
    "created_at"  TEXT,
    "created_by"  TEXT,

    CONSTRAINT "profile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "profile_code_key" ON "profile"("code");

CREATE TABLE "user_profile" (
    "id"         SERIAL NOT NULL,
    "user_id"    INTEGER NOT NULL,
    "profile_id" INTEGER NOT NULL,

    CONSTRAINT "user_profile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "user_profile_user_id_profile_id_key" ON "user_profile"("user_id", "profile_id");
CREATE INDEX "ix_user_profile_user" ON "user_profile"("user_id");
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_profile_id_fkey"
    FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE "app_user" ADD COLUMN "active_profile_id" INTEGER;
ALTER TABLE "app_user" ADD CONSTRAINT "app_user_active_profile_id_fkey"
    FOREIGN KEY ("active_profile_id") REFERENCES "profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- ============================================================================= seed the 6 profiles

INSERT INTO "profile" ("code", "name", "description", "role_centre", "icon", "sort", "is_default", "is_system", "created_by")
VALUES
  ('SUPER',           'Super Role Centre',                  'Full cross-society overview — the original dashboard.',                     'SUPER',           '▤', 10, 1, 1, 'system'),
  ('CRM',             'Client Relationship Management',     'Membership growth, the application pipeline and member care.',              'CRM',             '👥', 20, 0, 1, 'system'),
  ('CREDIT',          'Credit Role Centre',                 'Loan portfolio, disbursements, arrears and sectorial lending.',             'CREDIT',          '💳', 30, 0, 1, 'system'),
  ('FOSA',            'FOSA Role Centre',                   'Teller cash, deposits and withdrawals, cheques and standing orders.',       'FOSA',            '💵', 40, 0, 1, 'system'),
  ('FINANCE_MANAGER', 'Finance Manager Role Centre',        'Profitability, the balance sheet, capital adequacy and approvals.',         'FINANCE_MANAGER', '📈', 50, 0, 1, 'system'),
  ('ACCOUNTANT',      'Accountant Role Centre',             'Journals, the trial balance, reconciliations and tax.',                     'ACCOUNTANT',      '📒', 60, 0, 1, 'system')
ON CONFLICT ("code") DO NOTHING;

-- ============================================================================= backfill existing users
-- Every existing user gets the Super profile and lands on it, so the app behaves exactly as before
-- until an admin assigns more. Guarded on an existing organisation so a fresh DB is seeded by
-- lib/seed.ts instead.

INSERT INTO "user_profile" ("user_id", "profile_id")
SELECT u.id, p.id
FROM "app_user" u
CROSS JOIN "profile" p
WHERE p.code = 'SUPER'
  AND EXISTS (SELECT 1 FROM "organisation")
  AND NOT EXISTS (SELECT 1 FROM "user_profile" up WHERE up.user_id = u.id AND up.profile_id = p.id);

UPDATE "app_user"
SET "active_profile_id" = (SELECT id FROM "profile" WHERE code = 'SUPER')
WHERE "active_profile_id" IS NULL
  AND EXISTS (SELECT 1 FROM "organisation");

-- ============================================================================= role-centre permission sets
-- Six new tailored Permission Sets so an admin can pair a matching permission set with a profile.
-- Existing roles are left untouched. The permission_set_line rows are generated from the same
-- ACTION lists lib/seed.ts uses for a fresh DB (scripts/gen-role-center-perms.ts) and appended
-- below by the implementation.

INSERT INTO "role" ("name", "description", "is_system")
VALUES
  ('Super Role Centre',          'Broad cross-society access — pairs with the Super role centre.', 0),
  ('CRM Officer',                'Membership, applications and member care — pairs with the CRM role centre.', 0),
  ('Credit Officer',             'Loans, collateral and guarantors — pairs with the Credit role centre.', 0),
  ('FOSA Officer',               'Teller and front-office operations — pairs with the FOSA role centre.', 0),
  ('Finance Manager',            'Reporting, approvals and oversight — pairs with the Finance Manager role centre.', 0),
  ('Accountant',                 'General ledger, journals, reconciliation and tax — pairs with the Accountant role centre.', 0)
ON CONFLICT ("name") DO NOTHING;

-- 558 permission_set_line rows across 6 role-centre permission sets.
INSERT INTO "permission_set_line"
  ("role_id", "object_type", "object_name", "read_perm", "insert_perm", "modify_perm", "delete_perm", "execute_perm")
SELECT r.id, g.object_type, g.object_name, g.r, g.i, g.m, g.d, g.e
FROM "role" r
JOIN (VALUES
  ('Super Role Centre', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_STATEMENTS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_APPLICATIONS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_EDITS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_EXITS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_ACTIVATIONS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_READMISSIONS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ACCOUNT_OPENING', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ACCOUNT_DEACTIVATION', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ACCOUNT_ACTIVATION', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_CHARGING', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'STANDING_ORDERS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'CHECKOFF_BATCHES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'FIXED_DEPOSITS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'CASH_MANAGEMENT', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'TELLER_TRANSACTIONS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'LIENS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'INTER_ACCOUNT_TRANSFERS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'BANKERS_CHEQUES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'CHEQUE_DEPOSITS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ENTRANCE_FEE_RECOVERY', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'MEMBER_STATUS_UPDATE', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'LOAN_CALCULATOR', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'COLLATERAL_APPLICATIONS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'COLLATERAL_REGISTER', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'COLLATERAL_RELEASES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'GUARANTOR_CHANGES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'GL', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'INVENTORY', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'FIXED_ASSETS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'RECEIVABLES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'PAYABLES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'CASH_MGMT', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'VAT_REPORTS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'FINANCIAL_REPORTS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ADMIN_AUDIT', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'PAGE', 'ADMIN_PROFILES', 0, 0, 0, 0, 1),
  ('Super Role Centre', 'TABLE', 'member', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'attachment', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_next_of_kin', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_nominee', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'savings_account', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'loan', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'txn', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_application', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'workflow_task', 0, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_application_next_of_kin', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_application_nominee', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_application_signatory', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_application_attachment', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_application_account_instruction', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_signatory', 0, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_next_of_kin', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_nominee', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_signatory', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_attachment', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_edit_account_instruction', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_exit', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_exit_line', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'loan_schedule', 0, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'journal', 1, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'journal_line', 1, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_activation_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_readmission_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'account_opening_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'account_deactivation_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'account_activation_request', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_charging', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'standing_order', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'checkoff_batch', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'checkoff_batch_line', 0, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'checkoff_calculation', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_fixed_deposit', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'member_fixed_deposit_schedule', 0, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'fosa_transaction', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'cash_denomination_line', 0, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'bank_account_ledger_entry', 1, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'teller_transaction', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_lien', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'inter_account_transfer', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'bankers_cheque', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'cheque_deposit', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'member_category', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'loan_guarantor', 0, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'loan_collateral', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'loan_appraisal', 0, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'loan_appraisal_factor', 0, 1, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'loan_calculator', 1, 1, 1, 1, 0),
  ('Super Role Centre', 'TABLE', 'collateral_application', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'collateral_application_attachment', 0, 1, 0, 1, 0),
  ('Super Role Centre', 'TABLE', 'collateral_register', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'collateral_release', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'loan_guarantor_change', 1, 1, 1, 0, 0),
  ('Super Role Centre', 'TABLE', 'gl_account', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'item', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'item_unit_of_measure', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'stockkeeping_unit', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'item_journal_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'item_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'item_application_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'location', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'unit_of_measure', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'inventory_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'product_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fixed_asset', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_depreciation_book', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_journal_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_class', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_subclass', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_location', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'depreciation_book', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'fa_setup', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'maintenance', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'customer', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'customer_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_terms', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_method', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'reminder_terms', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'reminder_level', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'finance_charge_terms', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'sales_receivables_setup', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'sales_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'sales_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_sales_document', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_sales_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'cust_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'detailed_cust_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'cash_receipt_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'cash_receipt_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'reminder_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'reminder_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vendor', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vendor_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'purchases_payables_setup', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'purchase_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'purchase_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_purchase_document', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_purchase_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vendor_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'detailed_vendor_ledger_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_journal_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_journal_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vat_posting_setup', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vat_product_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vat_business_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'vat_entry', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'bank_account', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'bank_acc_posting_group', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'bank_reconciliation', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'bank_rec_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'currency', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'currency_exchange_rate', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'external_bank', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'external_bank_branch', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'cash_management_setup', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'receipt_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'receipt_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_receipt', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_receipt_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_voucher_header', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'payment_voucher_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_payment_voucher', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'posted_payment_voucher_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'wht_certificate', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'wht_certificate_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'financial_report', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'acc_schedule_name', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'acc_schedule_line', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'column_layout_name', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'column_layout', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'audit_log', 1, 0, 0, 0, 0),
  ('Super Role Centre', 'TABLE', 'profile', 1, 0, 0, 0, 0),
  ('CRM Officer', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_STATEMENTS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_APPLICATIONS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_EDITS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_EXITS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_ACTIVATIONS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_READMISSIONS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'ACCOUNT_OPENING', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'ACCOUNT_DEACTIVATION', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'ACCOUNT_ACTIVATION', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_CHARGING', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'STANDING_ORDERS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'MEMBER_STATUS_UPDATE', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'ENTRANCE_FEE_RECOVERY', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'FIXED_DEPOSITS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'COLLATERAL_APPLICATIONS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'COLLATERAL_REGISTER', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'COLLATERAL_RELEASES', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'GUARANTOR_CHANGES', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('CRM Officer', 'TABLE', 'member', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'attachment', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_next_of_kin', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_nominee', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'savings_account', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'loan', 1, 0, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'txn', 1, 1, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'member_application', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'workflow_task', 0, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'member_application_next_of_kin', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_application_nominee', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_application_signatory', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_application_attachment', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_application_account_instruction', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_signatory', 0, 1, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'member_edit_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'member_edit_next_of_kin', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_edit_nominee', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_edit_signatory', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_edit_attachment', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_edit_account_instruction', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'member_exit', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'member_exit_line', 0, 1, 0, 1, 0),
  ('CRM Officer', 'TABLE', 'loan_schedule', 0, 0, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'journal', 0, 1, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'journal_line', 0, 1, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'member_activation_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'member_readmission_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'account_opening_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'account_deactivation_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'account_activation_request', 1, 1, 1, 0, 0),
  ('CRM Officer', 'TABLE', 'member_charging', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'standing_order', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'member_category', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'member_fixed_deposit', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'collateral_application', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'collateral_register', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'collateral_release', 1, 0, 0, 0, 0),
  ('CRM Officer', 'TABLE', 'loan_guarantor_change', 1, 0, 0, 0, 0),
  ('Credit Officer', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'MEMBER_STATEMENTS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'LOAN_CALCULATOR', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'COLLATERAL_APPLICATIONS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'COLLATERAL_REGISTER', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'COLLATERAL_RELEASES', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'GUARANTOR_CHANGES', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'CHECKOFF_BATCHES', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'FIXED_DEPOSITS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'GL', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'PAGE', 'FINANCIAL_REPORTS', 0, 0, 0, 0, 1),
  ('Credit Officer', 'TABLE', 'member', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'savings_account', 1, 0, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'loan', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'txn', 1, 1, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'loan_guarantor', 0, 1, 1, 1, 0),
  ('Credit Officer', 'TABLE', 'loan_collateral', 0, 1, 0, 1, 0),
  ('Credit Officer', 'TABLE', 'loan_appraisal', 0, 1, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'loan_appraisal_factor', 0, 1, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'workflow_task', 0, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'attachment', 0, 1, 0, 1, 0),
  ('Credit Officer', 'TABLE', 'journal', 1, 1, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'journal_line', 1, 1, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'loan_schedule', 0, 1, 1, 1, 0),
  ('Credit Officer', 'TABLE', 'standing_order', 0, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'loan_calculator', 1, 1, 1, 1, 0),
  ('Credit Officer', 'TABLE', 'collateral_application', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'collateral_application_attachment', 0, 1, 0, 1, 0),
  ('Credit Officer', 'TABLE', 'collateral_register', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'collateral_release', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'loan_guarantor_change', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'checkoff_batch', 1, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'checkoff_batch_line', 0, 1, 1, 0, 0),
  ('Credit Officer', 'TABLE', 'checkoff_calculation', 0, 1, 0, 1, 0),
  ('Credit Officer', 'TABLE', 'member_fixed_deposit', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'gl_account', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'financial_report', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'acc_schedule_name', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'acc_schedule_line', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'column_layout_name', 1, 0, 0, 0, 0),
  ('Credit Officer', 'TABLE', 'column_layout', 1, 0, 0, 0, 0),
  ('FOSA Officer', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'MEMBER_STATEMENTS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'TELLER_TRANSACTIONS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'CASH_MANAGEMENT', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'LIENS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'INTER_ACCOUNT_TRANSFERS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'BANKERS_CHEQUES', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'CHEQUE_DEPOSITS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'STANDING_ORDERS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'FIXED_DEPOSITS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'MEMBER_CHARGING', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'ENTRANCE_FEE_RECOVERY', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'MEMBER_STATUS_UPDATE', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'ACCOUNT_OPENING', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'ACCOUNT_ACTIVATION', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'ADMIN_POOL_DENOMINATIONS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'ADMIN_TELLER_SETUP', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('FOSA Officer', 'TABLE', 'member', 1, 0, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'savings_account', 1, 0, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'loan', 1, 0, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'txn', 1, 1, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'journal', 0, 1, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'journal_line', 0, 1, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'teller_transaction', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'cash_denomination_line', 0, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'workflow_task', 0, 1, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'bank_account_ledger_entry', 0, 1, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'fosa_transaction', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'member_lien', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'inter_account_transfer', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'bankers_cheque', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'cheque_deposit', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'standing_order', 1, 1, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'member_fixed_deposit', 1, 1, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'member_charging', 1, 1, 1, 1, 0),
  ('FOSA Officer', 'TABLE', 'member_category', 1, 0, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'account_opening_request', 1, 1, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'account_activation_request', 1, 1, 1, 0, 0),
  ('FOSA Officer', 'TABLE', 'denomination', 1, 0, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'teller_setup', 1, 0, 0, 0, 0),
  ('FOSA Officer', 'TABLE', 'loan_schedule', 0, 0, 1, 0, 0),
  ('Finance Manager', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'MEMBER_STATEMENTS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'MEMBER_EXITS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'CHECKOFF_BATCHES', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'GL', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'FINANCIAL_REPORTS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'RECEIVABLES', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'PAYABLES', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'CASH_MGMT', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'INVENTORY', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'FIXED_ASSETS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'VAT_REPORTS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'TELLER_TRANSACTIONS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'CASH_MANAGEMENT', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'LIENS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'INTER_ACCOUNT_TRANSFERS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'BANKERS_CHEQUES', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'CHEQUE_DEPOSITS', 0, 0, 0, 0, 1),
  ('Finance Manager', 'PAGE', 'ADMIN_AUDIT', 0, 0, 0, 0, 1),
  ('Finance Manager', 'TABLE', 'member', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'savings_account', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'loan', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'txn', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'member_exit', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'checkoff_batch', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'journal', 1, 1, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'journal_line', 1, 1, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'gl_account', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'accounting_period', 0, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'bank_reconciliation', 1, 1, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'bank_account_ledger_entry', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'financial_report', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'acc_schedule_name', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'acc_schedule_line', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'column_layout_name', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'column_layout', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'customer', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'customer_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_terms', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_method', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'reminder_terms', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'reminder_level', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'finance_charge_terms', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'sales_receivables_setup', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'sales_header', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'sales_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_sales_document', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_sales_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'cust_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'detailed_cust_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'cash_receipt_header', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'cash_receipt_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'reminder_header', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'reminder_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vendor', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vendor_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'purchases_payables_setup', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'purchase_header', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'purchase_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_purchase_document', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_purchase_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vendor_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'detailed_vendor_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_journal_header', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_journal_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vat_posting_setup', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vat_product_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vat_business_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'vat_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'bank_account', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'bank_acc_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'bank_rec_line', 1, 1, 1, 1, 0),
  ('Finance Manager', 'TABLE', 'currency', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'currency_exchange_rate', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'external_bank', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'external_bank_branch', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'cash_management_setup', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'receipt_header', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'receipt_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_receipt', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_receipt_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_voucher_header', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'payment_voucher_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_payment_voucher', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'posted_payment_voucher_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'wht_certificate', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'wht_certificate_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'item', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'item_unit_of_measure', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'stockkeeping_unit', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'item_journal_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'item_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'item_application_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'location', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'unit_of_measure', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'inventory_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'product_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fixed_asset', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_depreciation_book', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_journal_line', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_ledger_entry', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_class', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_subclass', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_location', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_posting_group', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'depreciation_book', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'fa_setup', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'maintenance', 1, 0, 0, 0, 0),
  ('Finance Manager', 'TABLE', 'teller_transaction', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'fosa_transaction', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'member_lien', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'inter_account_transfer', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'bankers_cheque', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'cheque_deposit', 1, 0, 1, 0, 0),
  ('Finance Manager', 'TABLE', 'audit_log', 1, 0, 0, 0, 0),
  ('Accountant', 'PAGE', 'GL', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'FINANCIAL_REPORTS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'REPORTS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'DASHBOARD', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'APPROVALS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'RECEIVABLES', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'PAYABLES', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'CASH_MGMT', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'VAT_REPORTS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'ADMIN_POOL_VAT', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'INVENTORY', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'FIXED_ASSETS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'SAVINGS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'LOANS', 0, 0, 0, 0, 1),
  ('Accountant', 'PAGE', 'MEMBERS', 0, 0, 0, 0, 1),
  ('Accountant', 'TABLE', 'journal', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'journal_line', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'gl_account', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'workflow_task', 0, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'change_log_entry', 0, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'bank_reconciliation', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'bank_account_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'accounting_period', 0, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'financial_report', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'acc_schedule_name', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'acc_schedule_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'column_layout_name', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'column_layout', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'customer', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'customer_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'payment_terms', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'payment_method', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'reminder_terms', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'reminder_level', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'finance_charge_terms', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'sales_receivables_setup', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'sales_header', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'sales_line', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_sales_document', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_sales_line', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'cust_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'detailed_cust_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'cash_receipt_header', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'cash_receipt_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'reminder_header', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'reminder_line', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'vendor', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'vendor_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'purchases_payables_setup', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'purchase_header', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'purchase_line', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_purchase_document', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_purchase_line', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'vendor_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'detailed_vendor_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'payment_journal_header', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'payment_journal_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'vat_posting_setup', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'vat_product_posting_group', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'vat_business_posting_group', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'vat_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'bank_account', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'bank_acc_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'bank_rec_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'currency', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'currency_exchange_rate', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'external_bank', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'external_bank_branch', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'cash_management_setup', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'receipt_header', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'receipt_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'posted_receipt', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_receipt_line', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'payment_voucher_header', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'payment_voucher_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'posted_payment_voucher', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'posted_payment_voucher_line', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'wht_certificate', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'wht_certificate_line', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'item', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'item_unit_of_measure', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'stockkeeping_unit', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'item_journal_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'item_ledger_entry', 1, 1, 1, 0, 0),
  ('Accountant', 'TABLE', 'item_application_entry', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'location', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'unit_of_measure', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'inventory_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'product_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'fixed_asset', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'fa_depreciation_book', 1, 0, 1, 0, 0),
  ('Accountant', 'TABLE', 'fa_journal_line', 1, 1, 1, 1, 0),
  ('Accountant', 'TABLE', 'fa_ledger_entry', 1, 1, 0, 0, 0),
  ('Accountant', 'TABLE', 'fa_class', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'fa_subclass', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'fa_location', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'fa_posting_group', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'depreciation_book', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'fa_setup', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'maintenance', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'savings_account', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'loan', 1, 0, 0, 0, 0),
  ('Accountant', 'TABLE', 'member', 1, 0, 0, 0, 0)
) AS g(role_name, object_type, object_name, r, i, m, d, e) ON g.role_name = r.name
WHERE EXISTS (SELECT 1 FROM "organisation")
ON CONFLICT ("role_id", "object_type", "object_name") DO NOTHING;

